### ISSUE TITLE
Assert.js error

### ISSUE THREAD

**Issue by JC-B** [dgarage/bitcoinrpcapp#1]
When executing ./rpc-cli, I get the error. Followed all steps in readme

assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: null == 'Error: Could not connect to bitcoin via RPC at host: localhost port: 8332 Error: connect ECONNREFUSED 127.0.0.1:8332'
    at bitcoin.getBlockHash (/Users/jc/workshops/BitcoinEdge/bitcoinrpcapp/scanner.js:26:20)
    at ClientRequest.req.on (/Users/jc/workshops/BitcoinEdge/bitcoinrpcapp/node_modules/bcrpc/index.js:133:5)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by anditto** [comment]
It looks like it can't connect to the Bitcoin RPC. Can you put up a log of you following the steps in README?

**Comment by JC-B** [comment]
So, the rpc_cli error is fixed now. I just repeated the entire process. And, it works :). But, I get a bunch of assertion errors in the npm test. Let me know what you think might be an issue

Here is the log of everything done
$ pwd
/Users/jc/workshops/BitcoinEdge

$ brew install node mongodb
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (caskroom/cask, homebrew/core).
==> Updated Formulae
armadillo           kompose             mg                  re2
frugal              libpqxx             micropython         redex
gnu-units           mariadb             node-build          resty
hyperscan           maxima              osm2pgrouting       vim
icoutils            mdds                pandoc              wireguard-tools

Warning: node 8.9.0 is already installed
Warning: mongodb 3.4.10 is already installed

$ brew services start mongodb
Service `mongodb` already started, use `brew services restart mongodb` to restart.

$ brew services restart mongodb
Stopping `mongodb`... (might take a while)
==> Successfully stopped `mongodb` (label: homebrew.mxcl.mongodb)
==> Successfully started `mongodb` (label: homebrew.mxcl.mongodb)

$ sudo npm install -g mocha
/usr/local/bin/mocha -> /usr/local/lib/node_modules/mocha/bin/mocha
/usr/local/bin/_mocha -> /usr/local/lib/node_modules/mocha/bin/_mocha
+ mocha@4.0.1

$ python --version
Python 3.6.3

$ ruby --version
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]

Then, installed bitcoin using https://github.com/bitcoin/bitcoin/blob/master/doc/build-osx.md
No errors (verified by running make clean)

$ cd bitcoin

$ git clone https://github.com/dgarage/bitcoinrpcapp.git
Cloning into 'bitcoinrpcapp'...
remote: Counting objects: 2021, done.
remote: Compressing objects: 100% (1407/1407), done.
remote: Total 2021 (delta 463), reused 2015 (delta 457), pack-reused 0
Receiving objects: 100% (2021/2021), 2.21 MiB | 1.92 MiB/s, done.
Resolving deltas: 100% (463/463), done.

$ cd bitcoinrpcapp

$ ls -ltr
total 240
drwxr-xr-x   6 jc  staff    204 Nov  1 13:05 models
-rwxr-xr-x   1 jc  staff    608 Nov  1 13:05 index.js
-rw-r--r--   1 jc  staff   1172 Nov  1 13:05 events.js
-rw-r--r--   1 jc  staff    787 Nov  1 13:05 debug.js
-rw-r--r--   1 jc  staff   2089 Nov  1 13:05 db.js
-rw-r--r--   1 jc  staff    468 Nov  1 13:05 config.js
-rw-r--r--   1 jc  staff   4629 Nov  1 13:05 cli.js
-rw-r--r--   1 jc  staff    505 Nov  1 13:05 bitcoin.js
-rw-r--r--   1 jc  staff   7196 Nov  1 13:05 api.js
-rw-r--r--   1 jc  staff   2061 Nov  1 13:05 README.md
-rw-r--r--   1 jc  staff   1784 Nov  1 13:05 utils.js
-rw-r--r--   1 jc  staff  26389 Nov  1 13:05 tests.js
-rw-r--r--   1 jc  staff   7486 Nov  1 13:05 scanner.js
lrwxr-xr-x   1 jc  staff      8 Nov  1 13:05 rpc-cli -> index.js
-rw-r--r--   1 jc  staff  13228 Nov  1 13:05 payment.js
-rw-r--r--   1 jc  staff    777 Nov  1 13:05 package.json
-rw-r--r--   1 jc  staff  12103 Nov  1 13:05 package-lock.json
drwxr-xr-x  17 jc  staff    578 Nov  1 13:05 node_modules

$ npm install
up to date in 0.27s

$ ./rpc-cli
available commands:
  create <amount> <content> Create a new invoice for <amount> bit coins, its contents described in <content>.
  list [<since>]            List all invoices updated after `since`. If no `since` is provided, lists all invoices in the system.
  info <invoiceid>          Display info about the given invoice.
  updates                   List all invoices that were updated since the last call.

$ npm test

> rpc-cli@1.0.0 test /Users/jc/workshops/BitcoinEdge/bitcoin/bitcoinrpcapp
> mocha tests.js



  db
    ✓ can be connected to

  bitcoind
    ✓ can be found

  bitcointest
    ✓ configures (605ms)
    ✓ works

  utxo generation
    ✓ obtains spendable outputs (2301ms)

  invoice
    1) can be created

  payment
    2) updates status to pending
    3) updates status to confirmed
    4) updates status to reorg
    5) sets disabledAmount for reorg
    6) restores status to pending
    7) restores status to confirmed

  invoice status
    8) is unpaid
    9) becomes paid
    10) becomes overpaid
    11) becomes pending_overpaid
    12) becomes pending_paid
    13) becomes partial
    14) becomes pending_partial

  reorg unconfirm then reconfirm into another block:
    ✓ partitions
    15) can create an invoice
    16) can pay an invoice
    17) populates history with observed transaction
    18) puts payment as unconfirmed after reorg
    19) detects reconfirm

  double spend (replace payment to other address)
    ✓ partitions
    20) submits invoice
    21) pays invoice
    22) populates history with observed transaction
    23) detects double spend

  double spend replace (payment to same address)
    ✓ partitions
    24) submits invoice
    25) pays invoice
    26) populates history with observed transaction
    27) detects double spend

  cleanup
    ✓ finds relevant invoices
    ✓ clears relevant payments
    ✓ clears relevant history
    ✓ clears relevant invoices

  bctest end
    ✓ shuts down (405ms)


  13 passing (55s)
  27 failing

  1) invoice
       can be created:
     Error: the string "You haven't written this!" was thrown, throw an Error :)
  

  2) payment
       updates status to pending:
     Error: the string "You haven't written this!" was thrown, throw an Error :)
  

  3) payment
       updates status to confirmed:
     AssertionError [ERR_ASSERTION]: undefined == true
      at Object.findById (models/invoice.js:98:9)
      at Object.updateInvoice (payment.js:56:23)
      at Object.info (api.js:57:17)
      at Object.infoS (node_modules/deasync/index.js:43:7)
      at Context.<anonymous> (tests.js:245:36)

  4) payment
       updates status to reorg:
     AssertionError [ERR_ASSERTION]: undefined == true
      at Object.findById (models/invoice.js:98:9)
      at Object.updateInvoice (payment.js:56:23)
      at Object.info (api.js:57:17)
      at Object.infoS (node_modules/deasync/index.js:43:7)
      at Context.<anonymous> (tests.js:260:36)

  5) payment
       sets disabledAmount for reorg:
     TypeError: Cannot read property 'disabledAmount' of undefined
      at Context.<anonymous> (tests.js:274:20)

  6) payment
       restores status to pending:
     AssertionError [ERR_ASSERTION]: undefined == true
      at Object.findById (models/invoice.js:98:9)
      at Object.updateInvoice (payment.js:56:23)
      at Object.info (api.js:57:17)
      at Object.infoS (node_modules/deasync/index.js:43:7)
      at Context.<anonymous> (tests.js:284:36)

  7) payment
       restores status to confirmed:
     AssertionError [ERR_ASSERTION]: undefined == true
      at Object.findById (models/invoice.js:98:9)
      at Object.updateInvoice (payment.js:56:23)
      at Object.info (api.js:57:17)
      at Object.infoS (node_modules/deasync/index.js:43:7)
      at Context.<anonymous> (tests.js:296:36)

  8) invoice status
       is unpaid:
     Error: the string "You haven't written this!" was thrown, throw an Error :)
  

  9) invoice status
       becomes paid:
     Error: the string "You haven't written this!" was thrown, throw an Error :)
  

  10) invoice status
       becomes overpaid:
     Error: the string "You haven't written this!" was thrown, throw an Error :)
  

  11) invoice status
       becomes pending_overpaid:
     Error: the string "You haven't written this!" was thrown, throw an Error :)
  

  12) invoice status
       becomes pending_paid:
     Error: the string "You haven't written this!" was thrown, throw an Error :)
  

  13) invoice status
       becomes partial:
     Error: the string "You haven't written this!" was thrown, throw an Error :)
  

  14) invoice status
       becomes pending_partial:
     Error: the string "You haven't written this!" was thrown, throw an Error :)
  

  15) reorg unconfirm then reconfirm into another block:
       can create an invoice:
     Error: the string "You haven't written this!" was thrown, throw an Error :)
  

  16) reorg unconfirm then reconfirm into another block:
       can pay an invoice:
     AssertionError [ERR_ASSERTION]: undefined == true
      at Object.findById (models/invoice.js:98:9)
      at Object.updateInvoice (payment.js:56:23)
      at Object.info (api.js:57:17)
      at Object.infoS (node_modules/deasync/index.js:43:7)
      at Context.<anonymous> (tests.js:378:36)

  17) reorg unconfirm then reconfirm into another block:
       populates history with observed transaction:
     AssertionError: expected false to be true
      at Context.<anonymous> (tests.js:408:74)

  18) reorg unconfirm then reconfirm into another block:
       puts payment as unconfirmed after reorg:
     Error: the string "timeout waiting for new block hash" was thrown, throw an Error :)
  

  19) reorg unconfirm then reconfirm into another block:
       detects reconfirm:
     AssertionError [ERR_ASSERTION]: undefined == true
      at Object.findById (models/invoice.js:98:9)
      at Object.updateInvoice (payment.js:56:23)
      at Object.info (api.js:57:17)
      at Object.infoS (node_modules/deasync/index.js:43:7)
      at Context.<anonymous> (tests.js:448:36)

  20) double spend (replace payment to other address)
       submits invoice:
     Error: the string "You haven't written this!" was thrown, throw an Error :)
  

  21) double spend (replace payment to other address)
       pays invoice:
     AssertionError [ERR_ASSERTION]: undefined == true
      at Object.findById (models/invoice.js:98:9)
      at Object.updateInvoice (payment.js:56:23)
      at Object.info (api.js:57:17)
      at Object.infoS (node_modules/deasync/index.js:43:7)
      at Context.<anonymous> (tests.js:489:36)

  22) double spend (replace payment to other address)
       populates history with observed transaction:
     AssertionError: expected false to be true
      at Context.<anonymous> (tests.js:532:74)

  23) double spend (replace payment to other address)
       detects double spend:
     AssertionError: expected false to be true
      at Context.<anonymous> (tests.js:567:24)

  24) double spend replace (payment to same address)
       submits invoice:
     Error: the string "You haven't written this!" was thrown, throw an Error :)
  

  25) double spend replace (payment to same address)
       pays invoice:
     AssertionError [ERR_ASSERTION]: undefined == true
      at Object.findById (models/invoice.js:98:9)
      at Object.updateInvoice (payment.js:56:23)
      at Object.info (api.js:57:17)
      at Object.infoS (node_modules/deasync/index.js:43:7)
      at Context.<anonymous> (tests.js:611:36)

  26) double spend replace (payment to same address)
       populates history with observed transaction:
     AssertionError: expected false to be true
      at Context.<anonymous> (tests.js:656:74)

  27) double spend replace (payment to same address)
       detects double spend:
     AssertionError: expected false to be true
      at Context.<anonymous> (tests.js:682:29)

**Comment by anditto** [comment]
Yes, it's working perfectly. Those errors are what you're supposed to fix. Have fun! :)

**Comment by anditto** [comment]
Oops, sorry I'm mistaken. Try pulling the latest version and run `npm update` and paste the output here.

**Comment by JC-B** [comment]
Thanks for your prompt responses.


$ git pull
remote: Counting objects: 3, done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 3 (delta 2), reused 3 (delta 2), pack-reused 0
Unpacking objects: 100% (3/3), done.
From https://github.com/dgarage/bitcoinrpcapp
   58d1669..e585d62  master     -> origin/master
Updating 58d1669..e585d62
Fast-forward
 package.json | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

$ npm update
+ bitcointest@0.4.5
removed 1 package, updated 1 package and moved 10 packages in 2.642s

$ npm test

> rpc-cli@1.0.0 test /Users/jc/workshops/BitcoinEdge/bitcoin/bitcoinrpcapp
> mocha tests.js



  db
    ✓ can be connected to

  bitcoind
    ✓ can be found

  bitcointest
    ✓ configures (624ms)
    ✓ works

  utxo generation
    ✓ obtains spendable outputs (176ms)

  invoice
    1) can be created

  payment
    2) updates status to pending
    3) updates status to confirmed
    4) updates status to reorg
    5) sets disabledAmount for reorg
    6) restores status to pending
    7) restores status to confirmed

  invoice status
    8) is unpaid
    9) becomes paid
    10) becomes overpaid
    11) becomes pending_overpaid
    12) becomes pending_paid
    13) becomes partial
    14) becomes pending_partial

  reorg unconfirm then reconfirm into another block:
    ✓ partitions (204ms)
    15) can create an invoice
    16) can pay an invoice
    17) populates history with observed transaction
    18) puts payment as unconfirmed after reorg
    19) detects reconfirm

  double spend (replace payment to other address)
    ✓ partitions
    20) submits invoice
    21) pays invoice
    22) populates history with observed transaction
    23) detects double spend

  double spend replace (payment to same address)
    ✓ partitions
    24) submits invoice
    25) pays invoice
    26) populates history with observed transaction
    27) detects double spend

  cleanup
    ✓ finds relevant invoices
    ✓ clears relevant payments
    ✓ clears relevant history
    ✓ clears relevant invoices

  bctest end
    ✓ shuts down (404ms)


  13 passing (40s)
  27 failing

  1) invoice
       can be created:
     Error: the string "You haven't written this!" was thrown, throw an Error :)
  

  2) payment
       updates status to pending:
     Error: the string "You haven't written this!" was thrown, throw an Error :)
  

  3) payment
       updates status to confirmed:
     AssertionError [ERR_ASSERTION]: undefined == true
      at Object.findById (models/invoice.js:98:9)
      at Object.updateInvoice (payment.js:56:23)
      at Object.info (api.js:57:17)
      at Object.infoS (node_modules/deasync/index.js:43:7)
      at Context.<anonymous> (tests.js:245:36)

  4) payment
       updates status to reorg:
     AssertionError [ERR_ASSERTION]: undefined == true
      at Object.findById (models/invoice.js:98:9)
      at Object.updateInvoice (payment.js:56:23)
      at Object.info (api.js:57:17)
      at Object.infoS (node_modules/deasync/index.js:43:7)
      at Context.<anonymous> (tests.js:260:36)

  5) payment
       sets disabledAmount for reorg:
     TypeError: Cannot read property 'disabledAmount' of undefined
      at Context.<anonymous> (tests.js:274:20)

  6) payment
       restores status to pending:
     AssertionError [ERR_ASSERTION]: undefined == true
      at Object.findById (models/invoice.js:98:9)
      at Object.updateInvoice (payment.js:56:23)
      at Object.info (api.js:57:17)
      at Object.infoS (node_modules/deasync/index.js:43:7)
      at Context.<anonymous> (tests.js:284:36)

  7) payment
       restores status to confirmed:
     AssertionError [ERR_ASSERTION]: undefined == true
      at Object.findById (models/invoice.js:98:9)
      at Object.updateInvoice (payment.js:56:23)
      at Object.info (api.js:57:17)
      at Object.infoS (node_modules/deasync/index.js:43:7)
      at Context.<anonymous> (tests.js:296:36)

  8) invoice status
       is unpaid:
     Error: the string "You haven't written this!" was thrown, throw an Error :)
  

  9) invoice status
       becomes paid:
     Error: the string "You haven't written this!" was thrown, throw an Error :)
  

  10) invoice status
       becomes overpaid:
     Error: the string "You haven't written this!" was thrown, throw an Error :)
  

  11) invoice status
       becomes pending_overpaid:
     Error: the string "You haven't written this!" was thrown, throw an Error :)
  

  12) invoice status
       becomes pending_paid:
     Error: the string "You haven't written this!" was thrown, throw an Error :)
  

  13) invoice status
       becomes partial:
     Error: the string "You haven't written this!" was thrown, throw an Error :)
  

  14) invoice status
       becomes pending_partial:
     Error: the string "You haven't written this!" was thrown, throw an Error :)
  

  15) reorg unconfirm then reconfirm into another block:
       can create an invoice:
     Error: the string "You haven't written this!" was thrown, throw an Error :)
  

  16) reorg unconfirm then reconfirm into another block:
       can pay an invoice:
     AssertionError [ERR_ASSERTION]: undefined == true
      at Object.findById (models/invoice.js:98:9)
      at Object.updateInvoice (payment.js:56:23)
      at Object.info (api.js:57:17)
      at Object.infoS (node_modules/deasync/index.js:43:7)
      at Context.<anonymous> (tests.js:378:36)

  17) reorg unconfirm then reconfirm into another block:
       populates history with observed transaction:
     AssertionError: expected false to be true
      at Context.<anonymous> (tests.js:408:74)

  18) reorg unconfirm then reconfirm into another block:
       puts payment as unconfirmed after reorg:
     Error: the string "timeout waiting for new block hash" was thrown, throw an Error :)
  

  19) reorg unconfirm then reconfirm into another block:
       detects reconfirm:
     AssertionError [ERR_ASSERTION]: undefined == true
      at Object.findById (models/invoice.js:98:9)
      at Object.updateInvoice (payment.js:56:23)
      at Object.info (api.js:57:17)
      at Object.infoS (node_modules/deasync/index.js:43:7)
      at Context.<anonymous> (tests.js:448:36)

  20) double spend (replace payment to other address)
       submits invoice:
     Error: the string "You haven't written this!" was thrown, throw an Error :)
  

  21) double spend (replace payment to other address)
       pays invoice:
     AssertionError [ERR_ASSERTION]: undefined == true
      at Object.findById (models/invoice.js:98:9)
      at Object.updateInvoice (payment.js:56:23)
      at Object.info (api.js:57:17)
      at Object.infoS (node_modules/deasync/index.js:43:7)
      at Context.<anonymous> (tests.js:489:36)

  22) double spend (replace payment to other address)
       populates history with observed transaction:
     AssertionError: expected false to be true
      at Context.<anonymous> (tests.js:532:74)

  23) double spend (replace payment to other address)
       detects double spend:
     AssertionError: expected false to be true
      at Context.<anonymous> (tests.js:567:24)

  24) double spend replace (payment to same address)
       submits invoice:
     Error: the string "You haven't written this!" was thrown, throw an Error :)
  

  25) double spend replace (payment to same address)
       pays invoice:
     AssertionError [ERR_ASSERTION]: undefined == true
      at Object.findById (models/invoice.js:98:9)
      at Object.updateInvoice (payment.js:56:23)
      at Object.info (api.js:57:17)
      at Object.infoS (node_modules/deasync/index.js:43:7)
      at Context.<anonymous> (tests.js:611:36)

  26) double spend replace (payment to same address)
       populates history with observed transaction:
     AssertionError: expected false to be true
      at Context.<anonymous> (tests.js:656:74)

  27) double spend replace (payment to same address)
       detects double spend:
     AssertionError: expected false to be true
      at Context.<anonymous> (tests.js:682:29)

**Comment by kallewoof** [comment]
Hi @JC-B -- that looks correct. The error stuff at the end threw us off for a moment, but it's the same on our end.

**Comment by JC-B** [comment]
Thank you for clarifying that
